name: CI

on:
    push:
        branches:
            - main
            - beta
    pull_request:
        branches:
            - main
            - beta

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22.x

            - run: npm install

            - name: Test Project Scaffolding & Build
              run: |
                  mkdir -p /tmp/test-ci-workflow
                  node bin/vertigis-workflow-sdk.js create /tmp/test-ci-workflow/sample-pack --no-skills
                  cd /tmp/test-ci-workflow/sample-pack
                  npm run build
                  test -f build/main.js
                  test -f build/activitypack.json

